### ISSUE TITLE
Markers / Regions?

### ISSUE THREAD

**Issue by LFSaw** [jamesb93/reapy#1]
wow, this is really straight forward to use! Thank you for publishing this!

I was wondering if it is already possible to add markers/regions; I briefly looked into an `.rpp` file with some regions in it and found that they are defined as follows:

```
<REAPER_PROJECT 0.1 "6.23/OSX64" 1614956713
[...]
  MARKER 2 0 "the name" 1 0 1 B {4BFA4AC6-FF0C-254E-9288-C065E8D20161}
  MARKER 2 2.00266666666667 "" 1 0 1 B
[...]
>
```

if not, are you planning to add those?

**Comment by jamesb93** [comment]
Yeah super doable. If you know python feel free to PR otherwise I'll take a look tonight.

Thanks for the kind feedback too :)

**Comment by LFSaw** [comment]
I'm a little shaky in my python, that's probably why I ask :P 
would be much appreciated, though!

all the best and keep up the good work!

**Comment by jamesb93** [comment]
Any other requests before I take a look this evening? Happy to implement a few things while I'm there!

**Comment by LFSaw** [comment]
hmm... markers and regions would be cool, otherwise maybe sub-tracks (dunno how difficult that is or if it is or if it already works), and track automation... :)

**Comment by jamesb93** [comment]
>  otherwise maybe sub-tracks (dunno how difficult that is or if it is or if it already works), and track automation...

I'll definitely look into it. Thanks!

**Comment by jamesb93** [comment]
Just digging through this now has made me rethink a few things. At the moment a hash table represents the properties for each state chunk. MARKERS are properties, but they are not uniquely named apart from their number (which is not a part of the property name itself). As such using a hash table seems inappropriate here because sometimes properties exist more than once:

```
MARKERS
MARKERS
MARKERS
```

etc...

**Comment by jamesb93** [comment]
```python
from reathon.nodes import *
from reathon.helper import marker

proj = Project(
    Track(isbus='1 1', trackheight='67'),
    Track(isbus='1 1', trackheight='67'),
    Track(isbus='2 -1', trackheight='30'),
    Track(isbus='1 1', trackheight='67'),
    Track(isbus='1 1', trackheight='67'),
    Track(isbus='2 -1', trackheight='30'),
)

proj.props.extend([
    marker(1, 0, 'first'),
    marker(2, 0.5, 'second')
])

proj.write('markers.rpp')
```

You can now add arbitrary non-unique properties to Nodes in the REAPER XML format. Before it was a dictionary, now its just a list so it supports anything.

To do folders it comes under the `isbus` argument. It's not intuitive but `'1 1'` is a folder `'0 0'` for tracks which inherit their parent and `'2 -1'` is the end of a folder.

Does this help?

**Comment by LFSaw** [comment]
cool! i'll try adap!
