### ISSUE TITLE
Support for adding VST to track and setting parameters

### ISSUE THREAD

**Issue by csteinmetz1** [jamesb93/reapy#6]
Hi, nice package!

I was wondering how difficult it would be to create a REAPER project and add a few audio tracks as in the demo, but also add certain VSTs to each track, along with setting the parameters of these VSTs. 

I will look into how this is handled in the `.rpp` file, but was curious if you had any thoughts. Thanks!

**Comment by jamesb93** [comment]
Hey @csteinmetz1!

VSTs are encoded as sub-elements of the `<TAKEFX>` blocks and look like this:

```
<VST "VST3: MEqualizer (MeldaProduction)" MEqualizer.vst3 0 "" 928022665{4D656C646170726F4D4165334D416533} ""
    iYBQN+5e7f4CAAAAAQAAAAAAAAACAAAAAAAAAAIAAAABAAAAAAAAAAIAAAAAAAAAAgQAAAEAAAAAABAA
    +QEAAAEAAAB42m1T0W6bMBR9z1dY3usKNsaAJaBqq3R7SLSoVO326AYnWHVsCmRJ+/W7QDPSbkJC4p5zj++5x6SXx51Bv1XTamczTD2CkbJrV2q7zfC+21wk+DKfpcv5
    y14a/QZE1XUAtugL0DG6cbZrnDEAzK18MqrMMGjMS925poCGDMcR+cpDhtHirqiN7jo1ABT6CQ0/l4MMMxZhtJTHxe2Pa+PWz6MMC6CogNXewHmyblVZwJdywxwrs99q
    e++ceZLNX8IAPZzciYBGhOA8HWWCPH3UZVct87Rw+2at0KpRG20AG9wT7Oepf6L4p6ZZ+q2RdZWntdO2Q+euu9caBl24Q1Eps8HoZ7/ROBAR+Azg6QXHrpcMcy8gLOCc
    JTSM37lRFMecMhElUPkFFQYlTkXCgohO3QNXcEEF1IkYuaHHYzgm6d/sA5d5hHJGeUyE4BNyPvnACkOWJDFlCQ8m1ujpu95WkymgxgI0RRj2AcLhF9wTLGKCx1zEQ7c/
    bmmWXjVKtn2cegc53rlD26fi94iV5hWuFGWo2DnXVVa1ABKPcIzGSDIMqT9qW7rD/TiItBYSPE8KvoZJb43cttcgHkLox35FjFASCDAdRf1I/6eFn2n+R/GrFZlW1d80
    JZ8HC6io3AGummsepNmrd1upP9kCj/6/f04++wNsowav+QEAAAAAAAB42m1T0W6bMBR9z1dY3usKNsaAJaBqq3R7SLSoVO326AYnWHVsCmRJ+/W7QDPSbkJC4p5zj++5
    x6SXx51Bv1XTamczTD2CkbJrV2q7zfC+21wk+DKfpcv5y14a/QZE1XUAtugL0DG6cbZrnDEAzK18MqrMMGjMS925poCGDMcR+cpDhtHirqiN7jo1ABT6CQ0/l4MMMxZh
    tJTHxe2Pa+PWz6MMC6CogNXewHmyblVZwJdywxwrs99qe++ceZLNX8IAPZzciYBGhOA8HWWCPH3UZVct87Rw+2at0KpRG20AG9wT7Oepf6L4p6ZZ+q2RdZWntdO2Q+eu
    u9caBl24Q1Eps8HoZ7/ROBAR+Azg6QXHrpcMcy8gLOCcJTSM37lRFMecMhElUPkFFQYlTkXCgohO3QNXcEEF1IkYuaHHYzgm6d/sA5d5hHJGeUyE4BNyPvnACkOWJDFl
    CQ8m1ujpu95WkymgxgI0RRj2AcLhF9wTLGKCx1zEQ7c/bmmWXjVKtn2cegc53rlD26fi94iV5hWuFGWo2DnXVVa1ABKPcIzGSDIMqT9qW7rD/TiItBYSPE8KvoZJb43c
    ttcgHkLox35FjFASCDAdRf1I/6eFn2n+R/GrFZlW1d80JZ8HC6io3AGummsepNmrd1upP9kCj/6/f04++wNsowav
    ADAAEAAAAA==
>
```

So the format is quite evident till one arrives at the horrendous hash of what I suspect are parameters just below the name and vst binary name 😱

I think the `928022665{4D656C646170726F4D4165334D416533}` is actually superfluous. In many cases across generating REAPER files you can omit this kind of stuff and REAPER generates it for you on first save/open. I don't have many ideas about how one would reasonably go about abstracting an interface around the parameters, except for maybe calling some presets that are already preconfigured.

**Comment by csteinmetz1** [comment]
Yes, that is what I feared! Thanks for those insights. Seems like using ReaScript is the most feasible way to do this atm without having to reverse engineer the way the plugin state is stored for each plugin.

**Comment by jamesb93** [comment]
From a REAPER [forum post](https://forum.cockos.com/showpost.php?p=592731&postcount=13):

> They're Base64 encodings of the VST plugin's save state. (So yes, serialized binary data.) The content of the save state is plugin-specific. You could probably decode some simple plugin's state by making a change and seeing what happens. See projectcontext.cpp in WDL for example Base64 encode/decode functions.

**Comment by jamesb93** [comment]
> Yes, that is what I feared! Thanks for those insights. Seems like using ReaScript is the most feasible way to do this atm without having to reverse engineer the way the plugin state is stored for each plugin.

unfortunately so :( If your programmatic construction of tracks is simple enough then you'll be served well by the Reascript API :)
